version: '3.8'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: people_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    networks:
      - my-network

  node-app:
    build: .    
    entrypoint: dockerize -wait tcp://db:3306 -timeout 30s node index.js
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: people_db
    volumes:
      - .:/usr/src/app
    tty: true
    networks:
      - my-network

  nginx:
    build:
      context: ./nginx    
    container_name: nginx    
    ports:
      - "8080:80"
    depends_on:
      - node-app        
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
